# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-20 19:01
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_bootstrap3', '0015_boostrap3wellplugin_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='boostrap3buttonplugin',
            name='background_color',
            field=colorfield.fields.ColorField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='boostrap3buttonplugin',
            name='text_color',
            field=colorfield.fields.ColorField(blank=True, max_length=18, null=True),
        ),
    ]
