# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 10:47
from __future__ import unicode_literals

import autoslug.fields
import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import djangocms_text_ckeditor.fields
import easy_thumbnails.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Business Type',
                'verbose_name_plural': 'Business Types',
            },
        ),
        migrations.CreateModel(
            name='ClientInterests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Client interest',
                'verbose_name_plural': 'Clients Interests',
            },
        ),
        migrations.CreateModel(
            name='SoftwareProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('short_description', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True)),
                ('meta_title', models.CharField(max_length=70)),
                ('meta_description', models.CharField(max_length=160)),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('description', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='software_product_sidebars', slotname='software_sidebar', to='cms.Placeholder')),
            ],
            options={
                'verbose_name': 'Software product',
                'verbose_name_plural': 'Software products',
            },
        ),
        migrations.CreateModel(
            name='SoftwareProductPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('short_description', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='website.SoftwareProduct')),
            ],
            options={
                'verbose_name': 'Software product pricing',
                'ordering': ['software', 'price'],
                'verbose_name_plural': 'Software products pricing',
            },
        ),
        migrations.AddField(
            model_name='appuser',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='appuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='appuser',
            name='receive_newsletter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='State / Province'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='business_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='website.BusinessType'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='interested_in',
            field=models.ManyToManyField(related_name='clients', to='website.ClientInterests'),
        ),
    ]
