# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('cms', '0016_auto_20160608_1535'),
        ('website', '0002_auto_20170207_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderBackgroundExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.Page')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_header', to='filer.Image', verbose_name='Page header')),
                ('public_extension', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_extension', to='website.HeaderBackgroundExtension')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Page background',
                'verbose_name_plural': 'Page backgrounds',
            },
        ),
    ]
