# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 16:38
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_headerbackgroundextension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwareproduct',
            name='logo',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='software_logos', to='filer.Image'),
        ),
    ]
