# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20170207_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareproduct',
            name='demo',
            field=models.FileField(blank=True, null=True, upload_to='downloads'),
        ),
    ]
