# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('website', '0005_softwareproduct_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareDownloadPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='website_softwaredownloadplugin', serialize=False, to='cms.CMSPlugin')),
                ('software', models.ForeignKey(help_text='Select a specific software product', on_delete=django.db.models.deletion.CASCADE, to='website.SoftwareProduct')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='SoftwarePricingPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='website_softwarepricingplugin', serialize=False, to='cms.CMSPlugin')),
                ('software', models.ForeignKey(help_text='Select a specific software product', on_delete=django.db.models.deletion.CASCADE, to='website.SoftwareProduct')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
