# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('website', '0006_softwaredownloadplugin_softwarepricingplugin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareSpecificPricingPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='website_softwarespecificpricingplugin', serialize=False, to='cms.CMSPlugin')),
                ('pricing', models.ForeignKey(help_text='Select a specific pricing for a software product', on_delete=django.db.models.deletion.CASCADE, to='website.SoftwareProductPricing')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
