# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_softwarespecificpricingplugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareproductpricing',
            name='is_best_seller',
            field=models.BooleanField(default=False),
        ),
    ]
