# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_softwareproductpricing_is_best_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareproductpricing',
            name='per',
            field=models.CharField(blank=True, help_text='Specify if pricing is per ... year, cpu, etc', max_length=255, null=True),
        ),
    ]
