# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20170208_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionboxplugin',
            name='cmsplugin_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='website_promotionboxplugin', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
