# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 19:48
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('website', '0011_auto_20170208_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionboxplugin',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotional_box_images', to='filer.Image'),
        ),
    ]
