# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20170329_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwareproductpricing',
            name='sku',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
