# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20170329_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareorder',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
