# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_softwareorder_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareorder',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='softwareorder',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='softwareorder',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
