# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20170330_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwareorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='website.SoftwareOrder'),
        ),
    ]
