# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_auto_20170330_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareproductpricing',
            name='is_service',
            field=models.BooleanField(default=False),
        ),
    ]
