# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 16:24
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('website', '0026_softwareproductpricing_is_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('sku', models.CharField(max_length=255, unique=True)),
                ('short_description', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Software modules',
                'verbose_name': 'Software module',
            },
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='sites',
            field=models.ManyToManyField(to='sites.Site'),
        ),
        migrations.AddField(
            model_name='softwaremodule',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='website.SoftwareProduct'),
        ),
    ]
