# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-16 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_softwareproductpricing_software_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwarepricingplugin',
            name='include_modules',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='softwarespecificpricingplugin',
            name='include_modules',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='softwareproductpricing',
            name='software_modules',
            field=models.ManyToManyField(related_name='pricings', to='website.SoftwareModule', verbose_name='Software modules'),
        ),
    ]
