# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-16 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_auto_20170516_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwaremodule',
            name='read_more_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='read_more_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
