# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-16 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_ordercart_orderitemcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercart',
            name='session_key',
            field=models.CharField(default='a', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
