# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-16 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_orderitemcart_software_pks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemcart',
            name='quantity',
        ),
    ]
