# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-16 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_softwareorderitem_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareproduct',
            name='additional_license_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
