# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-16 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_softwarespecificpricingplugin_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwarepricingplugin',
            name='template',
            field=models.CharField(choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal')], default='vertical', max_length=20),
        ),
    ]
