# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-16 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_softwarepricingplugin_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemcart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
