# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-23 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('website', '0042_orderitemcart_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightedMenuExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.TextField(verbose_name='Hex color code e.g. (#cc0000)')),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.Page')),
                ('public_extension', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_extension', to='website.HighlightedMenuExtension')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
