# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-23 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_highlightedmenuextension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlightedmenuextension',
            name='color',
            field=models.CharField(max_length=10, verbose_name='Hex color code e.g. (#cc0000)'),
        ),
    ]
