# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-29 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('website', '0044_auto_20170623_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColoredAreaBox',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='website_coloredareabox', serialize=False, to='cms.CMSPlugin')),
                ('include_container', models.BooleanField(default=True, help_text='Leave cheched only for full width areas')),
                ('style', models.CharField(choices=[('.more-features', 'Dark brown'), ('.more-info', 'Light brown'), ('.testimonials', 'Mpez'), ('.pricing', 'White')], default='.more-features', max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
