# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-29 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_auto_20170629_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coloredareabox',
            name='style',
            field=models.CharField(choices=[('more-features', 'Dark brown'), ('more-info', 'Light brown'), ('testimonials', 'Mpez'), ('pricing', 'White padded'), ('', 'Plain')], default='.more-features', max_length=50),
        ),
    ]
