# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-09 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0047_auto_20170629_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='synced_with_mailchimp',
            field=models.BooleanField(default=False),
        ),
    ]
