# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-21 15:22
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0048_appuser_synced_with_mailchimp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='e.g. +41524204242', max_length=128),
        ),
    ]
