# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-08 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0052_auto_20170908_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwareorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
