# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-10 07:27
from __future__ import unicode_literals

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0053_auto_20170908_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionboxplugin',
            name='info',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True),
        ),
    ]
