# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-17 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('website', '0055_coloredareabox_padding'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadSoftwareButton',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='website_downloadsoftwarebutton', serialize=False, to='cms.CMSPlugin')),
                ('software', models.ForeignKey(help_text='Select a specific software product', on_delete=django.db.models.deletion.CASCADE, to='website.SoftwareProduct')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
