# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-17 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0056_downloadsoftwarebutton'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadsoftwarebutton',
            name='css_class',
            field=models.CharField(default='btn btn-danger btn-lg', max_length=100),
        ),
        migrations.AddField(
            model_name='downloadsoftwarebutton',
            name='title',
            field=models.CharField(default='Download free trial', max_length=100),
        ),
    ]
