# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-31 20:27
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0059_auto_20180831_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwaredownloadplugin',
            name='button_text_color',
            field=colorfield.fields.ColorField(blank=True, max_length=18),
        ),
        migrations.AddField(
            model_name='softwarepricingplugin',
            name='add_to_cart_text_color',
            field=colorfield.fields.ColorField(blank=True, max_length=18),
        ),
        migrations.AddField(
            model_name='softwarepricingplugin',
            name='buy_now_text_color',
            field=colorfield.fields.ColorField(blank=True, max_length=18),
        ),
        migrations.AddField(
            model_name='softwarespecificpricingplugin',
            name='add_to_cart_text_color',
            field=colorfield.fields.ColorField(blank=True, max_length=18),
        ),
        migrations.AddField(
            model_name='softwarespecificpricingplugin',
            name='buy_now_text_color',
            field=colorfield.fields.ColorField(blank=True, max_length=18),
        ),
    ]
