# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-31 20:51
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0061_auto_20180831_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='coloredareabox',
            name='background_color',
            field=colorfield.fields.ColorField(blank=True, help_text='Use specific color to override style background color', max_length=18),
        ),
    ]
