# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-31 20:54
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0062_coloredareabox_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadsoftwarebutton',
            name='button_color',
            field=colorfield.fields.ColorField(blank=True, max_length=18),
        ),
        migrations.AddField(
            model_name='downloadsoftwarebutton',
            name='button_text_color',
            field=colorfield.fields.ColorField(blank=True, max_length=18),
        ),
    ]
