# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-20 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0064_auto_20180920_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionboxplugin',
            name='text_color',
        ),
    ]
