# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-20 19:06
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0065_remove_promotionboxplugin_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightedmenuextension',
            name='button_background_color',
            field=colorfield.fields.ColorField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='highlightedmenuextension',
            name='button_like',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='highlightedmenuextension',
            name='color',
            field=colorfield.fields.ColorField(blank=True, max_length=18, null=True),
        ),
    ]
